---
- hosts: your_aws_instance
  become: yes
  tasks:
    - name: Download k3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install_k3s.sh
        mode: '0755'

    - name: Install k3s
      command: /tmp/install_k3s.sh